"""Add booking fields to application

Revision ID: 02dc6a553ae1
Revises: 8944350984d9
Create Date: 2026-02-10 20:51:55.676689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dc6a553ae1'
down_revision: Union[str, Sequence[str], None] = '8944350984d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'scheduled_at')
    op.drop_column('applications', 'decision_reason')
    op.drop_column('applications', 'match_score')
    # ### end Alembic commands ###
