"""Add structured_data to resume

Revision ID: 8944350984d9
Revises: bef167f2bcd7
Create Date: 2026-02-10 20:43:38.014750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8944350984d9'
down_revision: Union[str, Sequence[str], None] = 'bef167f2bcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('structured_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'structured_data')
    # ### end Alembic commands ###
