"""Add user fields

Revision ID: bef167f2bcd7
Revises: 7c119ef245b3
Create Date: 2026-02-10 20:28:04.022994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef167f2bcd7'
down_revision: Union[str, Sequence[str], None] = '7c119ef245b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.String(), nullable=True))
    
    # Create Enum type
    subscription_tier = sa.Enum('FREE', 'PRO', 'EXPERT', name='subscriptiontier')
    subscription_tier.create(op.get_bind())
    
    op.add_column('users', sa.Column('subscription_tier', subscription_tier, nullable=True))
    op.add_column('users', sa.Column('daily_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('quota_used_today', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_column('users', 'quota_used_today')
    op.drop_column('users', 'daily_quota')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###
